# Generated by Django 3.2 on 2021-04-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210417_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_bank_verified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='username'),
        ),
    ]
