# Generated by Django 3.2 on 2021-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.ImageField(upload_to='Posts')),
                ('Description', models.TextField()),
            ],
        ),
    ]
