# Generated by Django 3.2 on 2021-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20210413_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
