# Generated by Django 3.2 on 2021-04-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_auto_20210414_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.profile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Likes',
            field=models.ManyToManyField(blank=True, related_name='Post_Likes', to='Base.Profile'),
        ),
    ]
