# Generated by Django 3.2 on 2021-04-16 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0005_auto_20210414_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Liked_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
