# Generated by Django 3.2 on 2021-04-17 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0006_posts_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Liked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
