# Generated by Django 3.2 on 2021-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_alter_posts_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Filter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
