# Generated by Django 3.2 on 2021-04-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_posts_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, null=True, upload_to='Posts')),
                ('Video', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='File1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File1', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File10', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File2', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File3', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File4', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File5', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File6', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File7', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File8', to='Base.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File9', to='Base.files'),
        ),
    ]
