# Generated by Django 3.2 on 2021-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_auto_20210421_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='File10Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File1Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File2Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File3Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File4Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File5Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File6Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File7Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File8Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='File9Type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File1',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File10',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File2',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File3',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File4',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File5',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File6',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File7',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File8',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='File9',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
