# Generated by Django 3.2 on 2021-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_auto_20210422_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
