# Generated by Django 3.2 on 2021-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30, unique=True)),
                ('Messages', models.ManyToManyField(blank=True, to='Base.Messages')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Chatrooms',
            field=models.ManyToManyField(blank=True, to='Base.Chatroom'),
        ),
    ]
