# Generated by Django 3.2 on 2021-04-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_auto_20210429_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='Messengers',
            field=models.ManyToManyField(blank=True, to='Base.Profile'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.profile'),
        ),
    ]
