# Generated by Django 3.2 on 2021-04-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_profile_uniquecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.chatroom'),
        ),
    ]
