# Generated by Django 3.2 on 2021-05-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_alter_messages_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, null=True, upload_to='Stories')),
                ('FileType', models.BooleanField(blank=True, default=False, null=True)),
                ('Filter', models.CharField(blank=True, max_length=30, null=True)),
                ('Text', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Time', models.TimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Stories',
            field=models.ManyToManyField(blank=True, to='Base.Stories'),
        ),
    ]
