# Generated by Django 3.2 on 2021-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0019_auto_20210505_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Followers',
            field=models.ManyToManyField(blank=True, related_name='Follower', to='Base.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Following',
            field=models.ManyToManyField(blank=True, to='Base.Profile'),
        ),
    ]
